import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import curatalLogo from "../public/logo.png";
import Footer from "@/components/Footer";
import NavbarSwitcher from "@/components/NavbarSwitcher";
import FooterSwitcher from "@/components/FooterSwitches";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <NavbarSwitcher/>
        {children}
      <FooterSwitcher/>
      </body>
    </html>
  );
}
